#!/bin/bash

language_names=(
  tree-sitter-python
  tree-sitter-javascript
)

mkdir -p tests/fixtures

for language in ${language_names[@]}; do
  language_dir=tests/fixtures/$language
  language_url=https://github.com/tree-sitter/$language

  if [ ! -d $language_dir ]; then
    git clone $language_url $language_dir --depth=1
  fi

  (
    cd $language_dir
    git fetch origin master --depth 1
    git reset --hard FETCH_HEAD
  )
done

if [ ! -d tests/fixtures/tree-sitter-fbdl ]; then
    git clone https://github.com/Functional-Bus-Description-Language/tree-sitter-fbdl.git tests/fixtures/tree-sitter-fbdl
fi
